### ISSUE TITLE
[Read mail] Select mail to mark as read from outlook, check mail from Tmail is still marked as unread

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#970] opened 2022-09-22 09:49 UTC
**Current behaviour:** 
I selected unread mails from Outlook to mark them as read. Then I got back to Tmail to view those mails, they were still under status of unread.

**Expected:**
The status of mail has to be the same from every mail clients.

**Comment by hoangdat** [comment] 2022-09-22 10:03
Hi @chibenwa @Arsnael any idea for this issue?
I still see it always in OpenPaaS, and still in Tmail also.

**Comment by Arsnael** [comment] 2022-09-22 10:16
Never seen this issue with TB... so I'm not sure how to reproduce. Can we have a little video if possible? Is it possible as well that outlook failed at updating email flags?

**Comment by chibenwa** [comment] 2022-09-22 10:57
@haftus98 take screenshots and share details allowing to know which message it is.

@haftus98 has the message been COPIED before ? Is there 1 mailbox where it is read, one mailbox where it is unread ?

@Arsnael inconsistencies between `messageIdTable` and `imapUidTable` ?

**Comment by hoangdat** [comment] 2022-09-23 03:16
any related to #929?

**Comment by Arsnael** [comment] 2022-09-23 03:52
I don't think it is... other issue you still could see unread counter emails in jmap because somehow there is some messages not showing... while they show on imap and if you read them then it fix the counter for jmap too.

Here it feels more like she reads messages on outlook (imap), and those message are still unread on tmail (jmap).

But I know sometimes we don't all speak the same language, thus asking for a screenshot or video so we can be sure we understand each other

**Comment by haftus98** [comment] 2022-09-23 07:36
https://user-images.githubusercontent.com/97084773/191912204-adcfb7f9-1956-43dd-8747-b92a78163ec8.mp4


I read mail from Outlook, then reload the page in Tmail but it was still marked as unread from Tmail

**Comment by Arsnael** [comment] 2022-09-26 02:03
So yep nothing to do with #929 (I think?)
Thanks @haftus98 for the video :)

**Comment by chibenwa** [comment] 2022-09-26 02:05
Is the email marked as read in OpenPaaS ?

Does pressing `ctrl + f5` solves the issue in TMail ?

**Comment by Arsnael** [comment] 2022-09-26 02:26
Might be more some isolated issue with Outlook? I have no problem doing this with Thunderbird and TMail for example

**Comment by chibenwa** [comment] 2022-09-26 05:30
Yes I may be thinking "cache issues"

Basicaly I suspect under some conditions TMail app badly refreshes its cache. That's the scope of my question...

**Comment by hoangdat** [comment] 2022-09-26 06:53
yes, for one week ago, I found that we have synchronization between JMAP and IMAP, but not before (I always see the read mail in IMAP is unread in JMAP). So I will test more with the case.

**Comment by hoangdat** [comment] 2022-09-26 16:05
please verify the issue with v0.3.15 (please make sure to clean out the Tmail before test)

**Comment by haftus98** [comment] 2022-09-30 10:09
[Untitled_ Sep 30,2022 4_37 PM.webm](https://user-images.githubusercontent.com/97084773/193247636-4698d32d-0306-4042-a2ef-a544230ee686.webm)

still bugging :((

**Comment by hoangdat** [comment] 2022-10-05 03:25
fixed with #1044

**Closed** 2022-11-25 10:58 UTC
Labels: bug, Critical
