### ISSUE TITLE
[Bug] Counters aren't updated

### ISSUE THREAD

**Issue by tprudentova** [linagora/tmail-flutter#3032] opened 2024-07-24 08:24 UTC
0.12.1 tested on Android, Firefox, Opera; mail.stg.lin-saas.com

1. Open Twake Mail  
2. Receive some messages
3. The counters aren't updated

<img width="1280" alt="Screenshot 2024-07-24 at 11 19 33" src="https://github.com/user-attachments/assets/412955f9-2334-4937-980d-a4ac6e7531ca">

![photo_2024-07-24_11-24-00](https://github.com/user-attachments/assets/8f90847d-1118-405d-8f71-96865c11f393)

![photo_2024-07-24_11-23-55](https://github.com/user-attachments/assets/080890f0-7295-48ae-a9ac-dfd936535946)

**Comment by chibenwa** [comment] 2024-07-24 09:19
This is a plateform related bug, diagnosed and fixed on CNB

![image](https://github.com/user-attachments/assets/583b19b4-9167-47df-ba92-c5b890148c31)

JMAP event processing is then not updated by IMAP pods 

VS CNB 

![image](https://github.com/user-attachments/assets/d7cebfce-d22a-4c02-92eb-3e6c05fa35a4)

here are the PRs to the relevant HELM chart changes

 - tmail-backend main: https://ci.linagora.com/linagora/lrs/saas/tools/helm-charts/tmail-backend/-/merge_requests/58
 - tmail-backend 5.0: https://ci.linagora.com/linagora/lrs/saas/tools/helm-charts/tmail-backend/-/merge_requests/57

I will rely on @ducnm0711 for updating preprod + prod. Here is the relevant OPS ticket. https://ci.linagora.com/linagora/lrs/saas/devops/-/issues/576

**Comment by chibenwa** [comment] 2024-07-25 07:54
Solved for reading mails.

@hoangdat 

![image](https://github.com/user-attachments/assets/ff3e49cf-5969-48ce-ad19-2ff14c675e14)
![image](https://github.com/user-attachments/assets/d3796f35-0fe4-4e18-bdf5-171f7df1e7ff)


Those are the requests done to resynchronise, after receiving an email.

Why the heck doesn't it does `Mailbox/changes` stuff?

**Comment by chibenwa** [comment] 2024-07-25 07:57
This is a **regression**

![image](https://github.com/user-attachments/assets/cecaced2-678d-4293-9676-b8860b03b0a4)

tmail.linagora.com works great. `linagora/tmail-web:v0.11.4003`

I propose we revert. I propose we QA more before releasing.

**Comment by hoangdat** [comment] 2024-07-25 07:59
no, still work in our side. not understand what are you saying



![Image](https://github.com/user-attachments/assets/bc13f573-e59d-4bdc-80e3-6888d282297c)

**Comment by chibenwa** [comment] 2024-07-25 08:24
> no f*** regression here

Innapropriate language.

It is specifically when receiving emails.

Also, the issue is **with the refresh button** that only refreshes emails while it should refresh mailboxes also!

CF


https://github.com/user-attachments/assets/819253a7-b44a-4c8e-b174-55075c93711e

(So IMO still a regression)

**Comment by hoangdat** [comment] 2024-07-25 08:30
Maybe configuration issue, not found configuration file for fcm in client side

**Comment by hoangdat** [comment] 2024-07-25 08:31
> (So IMO still a regression)

By the way, what is the definition of `regression`?

**Comment by chibenwa** [comment] 2024-07-25 08:35
![image](https://github.com/user-attachments/assets/dfe51d49-604f-4675-b383-6f7467492b1c)

IE it worked before and now not any longer

**Comment by chibenwa** [comment] 2024-07-25 08:36
> Maybe configuration issue, not found configuration file for fcm in client side

We should resync mailboxes when I click that button, **regardless of FCM**.

BTW there's likely something with FCM too, yes.

**Comment by hoangdat** [comment] 2024-07-25 11:16
> We should resync mailboxes when I click that button, regardless of FCM. So this is still an issue.

I will separate this into other `improvement` ticket, not a regression: https://github.com/linagora/tmail-flutter/issues/3050


> BTW there's likely something with FCM too, yes.

Real time update is under investigating. A weird behavior between canary and staging (same front-end version)

**Comment by hoangdat** [comment] 2024-07-25 11:55
hi @chibenwa , please enable `com:linagora:params:jmap:firebase:push` capability for STG + Prod of TWP. We will unblock this issue

**Comment by chibenwa** [comment] 2024-07-25 21:41
hi @ducnm0711 (with maybe help of @quantranhong1999 )  , please enable com:linagora:params:jmap:firebase:push capability for STG + Prod of TWP. We will unblock this issue

**Comment by hoangdat** [comment] 2024-07-26 04:44
Clear the cache. Well fixed.

**Comment by tprudentova** [comment] 2024-08-12 09:51
email.linagora.com

https://github.com/user-attachments/assets/b269809c-fb3d-43f0-ab47-f5dc4d0a4993

IMO we need to refresh counters when user clicks on the Refresh button. Why is this considered a feature?.. Looks like a bug to me

**Comment by hoangdat** [comment] 2024-08-12 10:20
Maybe a brand-new browser, you still not have permission for this. Please check notification  settings

**Comment by tprudentova** [comment] 2024-08-12 11:24
https://github.com/user-attachments/assets/58813e37-f222-45d5-bbb7-b396132927d2

I've used this browser for like 6 years on this laptop, but the counters are still not updated. How are the counters connected to the notification settings though?..

**Comment by tprudentova** [comment] 2024-08-26 09:33
Expected behaviour: 
When I click the Refresh button, the counters are updated as well as the letters feed

**Closed** 2024-08-30 05:15 UTC
Labels: bug, TWP, staging, blocker
