### ISSUE TITLE
[Attachment/staging] cannot attach image on mobile and web

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1323] opened 2022-12-15 09:16 UTC
**Description**
I attached an image and it took long time to attach successfully.

**Video**

https://user-images.githubusercontent.com/97084773/207821147-65f66b76-7ff7-46b4-9636-6bd626e7a926.mp4

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/97084773/207824674-c38aff6d-d434-4b20-8708-cf39890fdfe7.png">

**Environment**
preproduction, v0.5.1, IOS 15.6.1, macos 12.6.1 (21G217)

**Comment by hoangdat** [comment] 2023-01-03 04:40
![Image](https://user-images.githubusercontent.com/6462404/210300978-45aa3948-c3fe-4940-bec7-eb066410ef9e.png)

**Comment by chibenwa** [comment] 2023-01-03 05:02
Does the request have the authorization header?

**Comment by hoangdat** [comment] 2023-01-03 05:58
still have, but need more invesigation

<img width="446" alt="image" src="https://user-images.githubusercontent.com/6462404/210306421-29c63136-142c-4b65-b117-a2154826e0c6.png">

**Comment by dab246** [comment] 2023-02-02 08:44
I investigated it. And detect this error from server `preprod`. We cannot upload to the server at this time. It always returns error `500 Internal Server Error`.



![Image](https://user-images.githubusercontent.com/80730648/216274530-c911a9c9-3ad0-45ce-b449-d92bb5736de7.png)

**Comment by Arsnael** [comment] 2023-02-06 06:33
FYI: We found the cause but not really sure what to do about it...

It seems it fails because James fails to create buckets for uploads, and if you try to upload to S3 an object to a non existing bucket, it fails...

Normally it should return a NoSuchBucketException , which when we catch it we would then retry with creating the bucket first, and it would pass

For some reason Swift from OVH on preprod does not seem to return this error anymore but a more generic one... the weird thing being here is that we use the same kind of object storage for prod and it still works fine... I really don't get it...

So we might just add a cron job on preprod that will check if the bucket or not for this week and next week exist and if not create it to workaround this, cause we consider it's a problem on ovh side.

**Comment by Arsnael** [comment] 2023-02-08 09:54
@dab246 @hoangdat that issue should be solved now.

I deployed and tested the workaround, seems fine for the moment. Don't hesitate to let me know if you have issues with that again

Please test again and close the issue if you deem it solved. Thanks :)

**Closed** 2023-02-19 12:26 UTC
Labels: bug, Major
