### ISSUE TITLE
[Offline] while app in offline, After click on send button in composer, dialog show, but when click outside the dialog, all disappear

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#2189] opened 2023-09-29 10:44 UTC
OS:  Android / IOS
Device: Mobile
TMail version: 0.9.3

### *Reproduce Step:
1, User A turn off network
2, User A click on [Composer] button
3, User A input correct all input fields
4, User click [Send] button
5, User click outside the Sending offline dialog

### **Actual:** 
After step 4
- System redirect user to previous screen 
- Sending offline dialog is displayed
After step5
- Dialog is disappeared
- The sending email is removed
- Sending email is not go in drafts or anywhere

### **Expected:** 
After step 4
- System keep displaying Composer screen
- Sending offline dialog is displayed
After step5
- Dialog is disappeared
- System keep displaying composer screen where user can continue writing email

https://github.com/linagora/tmail-flutter/assets/124866146/890cfac2-02d7-4422-a515-230458ceaadf

**Comment by dab246** [comment] 2023-10-02 02:18
It seems you are misunderstanding something here. If you do not perform any action on dialog. Looks like you've ignored it, and we haven't done anything about it yet.

**Comment by QuangHoang1210** [comment] 2023-10-02 02:21
@dab246  This is UX supportive. We should let user keep continue the writing email actions in case closing dialog once click outisde.

Orther way we can prevent user click outside the dialog.

**Comment by hoangdat** [comment] 2023-10-02 02:55
- [ ] keep composer available before click on proceed
- [ ] `cancel`- `close`

**Comment by QuangHoang1210** [comment] 2023-10-16 19:19
**-> Passed on Android 

-> Failed on IOS**

### ENV: IOS - Tmail 0.10.1

### Precondition: Turn off Wifi

### Reproduce step:
1, User send an email in offline state

### Actual: 
- System not showing dialog but "Email being sent" toast will be displayed

### Expected:
- System show dialog Sending Offline Process normally and same Android behaviour

https://github.com/linagora/tmail-flutter/assets/124866146/866d50ac-bbbc-4b0a-b481-0317a406bf97

**Comment by hoangdat** [comment] 2023-10-17 02:59
Only in iOS:

- Dialog the same with offline but the `Proceed` button replace by `Save to Draft`
- Title: `You are in offline mode`
- Message: `The message will be Save to Draft. You can try again when being online.`
- Buttons: `Cancel` `Save to Draft`.

**Closed** 2023-12-07 14:02 UTC
Labels: bug, Critical, Offline mode
