### ISSUE TITLE
System mailboxes are not sorted

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#322] opened 2022-03-11 10:49 UTC
INBOX should be first...

**Comment by chibenwa** [comment] 2022-03-11 10:51
![20220311_175010](https://user-images.githubusercontent.com/6928740/157853376-897936ac-5987-4012-b372-23527d97f0ab.jpg)

**Comment by Arsnael** [comment] 2022-03-15 03:14
Yes weird I noticed that too and I thought I fixed it a while ago... Regression?

**Comment by hoangdat** [comment] 2022-03-15 03:35
Yes, I will try more. But don't need to weird, because the data flow of web-mail not similar to the mobile, because web-mail does not use cache.

**Comment by Arsnael** [comment] 2022-03-15 04:58
Yes I confirm on mobile I still have the correct behavior. Thanks for the explanation @hoangdat

**Comment by hoangdat** [comment] 2022-03-16 15:18
Sad news, it's my fault when build the tree for default mailbox. But good news, our cache also work in browser :)

> Yes I confirm on mobile I still have the correct behavior. 

your version is outdate :). Maybe at the end of this week, new version will be released

**Comment by chibenwa** [comment] 2022-03-17 02:12
:+1:

**Closed** 2022-04-08 10:42 UTC
Labels: bug, Medium
