### ISSUE TITLE
[Mail] sending mail from GMail receives the weird mail

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1076] opened 2022-10-13 09:09 UTC
**Description**
I sent mail from GMail to Tmail, from Gmail I received a weird mail.

![image](https://user-images.githubusercontent.com/97084773/195555122-e41ca7bb-ffcc-457a-84cf-b43be5dab677.png)

**Comment by haftus98** [comment] 2022-10-13 09:11
@chibenwa

**Comment by chibenwa** [comment] 2022-10-13 09:33
Can't reproduce.

It's related to the infra, and not to TMail as a product.

(email trust is a complicated thing)

closing...

**Closed by chibenwa** 2022-10-13 09:33 UTC
Labels: bug, Critical
