### ISSUE TITLE
Verify that all strings are registered for translation

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#415] opened 2022-03-29 02:01 UTC
### Description

```
A quick remark: Please pay attention to use English/French words. Please choose between them but not both at the same time. Example "EDIT" then you have "Annuler"
```

Credit: Yazid Benazzouz

**Comment by chibenwa** [comment] 2022-03-29 02:02
@Kevinle2312 can you please do a review of what is translated, and not translated and list it in the ticket?

**Comment by hoangdat** [comment] 2022-03-29 02:33
@chibenwa that mean: `Edit` show when user chooses French?

**Comment by chibenwa** [comment] 2022-03-29 04:01
Yes

**Comment by chibenwa** [comment] 2022-03-29 04:02
We IMO need a review of what's not registered for translation.

**Comment by hoangdat** [comment] 2022-03-29 04:02
okie, let me check. I will standalize the way we work with Weblate

**Comment by Kevinle2312** [comment] 2022-03-29 06:43
> 

Yes I will do it.

**Comment by hoangdat** [comment] 2022-03-29 09:45
> > 
> 
> Yes I will do it.

no need to action. I fixed this with new configuration in Weblate.

Root cause: `Edit` and some later string are not registered to translate.

I will close this issue and wait contribution in `weblate` to have it in production.

**Closed by hoangdat** 2022-03-29 09:45 UTC
Labels: bug
