### ISSUE TITLE
[Reply/Responding] Reply screen is display not smoothly, it's lagging

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1469] opened 2023-02-17 22:20 UTC
OS: Only on IOS
Device: Mobile Iphone XS Max
TMail version: 0.7.0

*Precondition: User already recieved an email which have image & attachment file
*Reproduce step:
1, Tap to open an email in inbox
2, Tap to Reply / Reply all button
3, Tap to Close icon

<Please watch until finished video>
Actual: It's lagging
Expected: It should be smoothly repsonde to another screen.

https://user-images.githubusercontent.com/124866146/219805346-4533834a-f762-4de5-8245-dffe4f497100.mp4

App crashed when reopen it frequently

https://user-images.githubusercontent.com/6462404/223308516-ee1fea73-3a63-4c81-9383-a1db37a1aa52.mp4

**Comment by hoangdat** [comment] 2023-02-19 12:56
@dev, please use profilling tool to measure the frame rate for this case.

**Comment by chibenwa** [comment] 2023-02-20 01:25
I suspect `close` animation to rely synchronously on `Email/set` done while saving the mail...

Expectation: asynchronous...

**Comment by dab246** [comment] 2023-03-07 07:47
`App crashed when reopen it frequently`

@hoangdat  
- I tried many times, constantly opening and closing `composer` on the virtual tablet. But still not seeing `crash` like your video. I guess because your device has low configuration, `RAM` memory is not enough when you run the application, leading to lack of `RAM` causing crash.
- If possible, please `debug` on your machine to detect errors from `console` and send `log` to us.

**Comment by hoangdat** [comment] 2023-03-09 08:49
Hi @dab246 
please check the log:
```
I/flutter (26561): ComposerController::_applySignature(): --<br><br>
I/flutter (26561): <div><span style="font-weight: bold; background-color: rgb(255, 255, 255);">Sent from TMail<br></span></div>
[InAppWebViewController] (android) WebView ID 18 calling "onConsoleMessage" using {messageLevel: 3, message: Uncaught SyntaxError: Invalid or unexpected token}
I/ViewRootImpl@19c5b46[MainActivity](26561): ViewPostIme key 0
I/ViewRootImpl@19c5b46[MainActivity](26561): ViewPostIme key 1
I/flutter (26561): ComposerController::_autoCreateEmailTag():inputToEmail: 
I/flutter (26561): ComposerController::_autoCreateEmailTag():inputCcEmail: 
I/flutter (26561): ComposerController::_autoCreateEmailTag():inputBccEmail: 
D/InputMethodManager(26561): HSIFW - flag : 0
[GETX] CLOSE TO ROUTE /composer
I/flutter (26561): ComposerController::_getEmailBodyText():MOBILE: 
I/flutter (26561): 
I/flutter (26561): ComposerController::_isEmailChanged(): newEmailBody: 
I/flutter (26561): 
I/flutter (26561): ComposerController::_isEmailChanged(): getContentEmail: 
I/flutter (26561): ComposerController::_isEmailChanged(): oldEmailBody: 
I/flutter (26561): ComposerController::_isEmailChanged(): isEmailBodyChanged: false
[GETX] "SendEmailInteractor" deleted from memory
E/flutter (26561): [ERROR:flutter/fml/platform/android/jni_util.cc(204)] java.lang.IllegalStateException: Platform view hasn't been initialized from the platform view channel.
E/flutter (26561): 	at io.flutter.plugin.platform.PlatformViewsController.initializePlatformViewIfNeeded(PlatformViewsController.java:1045)
E/flutter (26561): 	at io.flutter.plugin.platform.PlatformViewsController.onDisplayPlatformView(PlatformViewsController.java:1115)
E/flutter (26561): 	at io.flutter.embedding.engine.FlutterJNI.onDisplayPlatformView(FlutterJNI.java:1380)
E/flutter (26561): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (26561): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (26561): 	at android.os.Looper.loop(Looper.java:206)
E/flutter (26561): 	at android.app.ActivityThread.main(ActivityThread.java:8653)
E/flutter (26561): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (26561): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/flutter (26561): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/flutter (26561): 
F/flutter (26561): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1486)] Check failed: fml::jni::CheckException(env). 
[GETX] "LocalFilePickerInteractor" deleted from memory
[GETX] "SaveEmailAsDraftsInteractor" deleted from memory
[GETX] "UpdateEmailDraftsInteractor" deleted from memory
[GETX] "FileUploader" deleted from memory
[GETX] "AttachmentUploadDataSourceImpl" deleted from memory
[GETX] "AttachmentUploadDataSource" deleted from memory
[GETX] "ComposerDataSourceImpl" deleted from memory
[GETX] "ComposerDataSource" deleted from memory
[GETX] "ComposerRepositoryImpl" deleted from memory
[GETX] "ComposerRepository" deleted from memory
[GETX] "UploadAttachmentInteractor" deleted from memory
[GETX] "UploadController" onDelete() called
[GETX] "UploadController" deleted from memory
[GETX] "RemoveComposerCacheOnWebInteractor" deleted from memory
[GETX] "SaveComposerCacheOnWebInteractor" deleted from memory
[GETX] "RichTextWebController" onDelete() called
[GETX] "RichTextWebController" deleted from memory
[GETX] "DownloadImageAsBase64Interactor" deleted from memory
[GETX] "RichTextMobileTabletController" onDelete() called
[GETX] "RichTextMobileTabletController" deleted from memory
[GETX] "ComposerController" onDelete() called
[GETX] "ComposerController" deleted from memory
F/libc    (26561): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 26561 (ndroid.teammail), pid 26561 (ndroid.teammail)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/gta3xlxx/gta3xl:11/RP1A.200720.012/T515XXU8CVL1:user/release-keys'
Revision: '4'
ABI: 'arm'
Timestamp: 2023-03-09 15:46:37+0700
pid: 26561, tid: 26561, name: ndroid.teammail  >>> com.linagora.android.teammail <<<
uid: 10264
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1486)] Check failed: fml::jni::CheckException(env). 
'
    r0  00000000  r1  000067c1  r2  00000006  r3  ffe0cad8
    r4  ffe0caec  r5  ffe0cad0  r6  000067c1  r7  0000016b
    r8  ffe0cad8  r9  ffe0cae8  r10 ffe0cb08  r11 ffe0caf8
    ip  000067c1  sp  ffe0caa8  lr  f0c77dd5  pc  f0c77de8
backtrace:
      #00 pc 00062de8  /apex/com.android.runtime/lib/bionic/libc.so (abort+172) (BuildId: fef5b751123147ea65bf3f4f798c9518)
      #01 pc 0131e6fb  /data/app/~~-9UawJwUN9MfcIn8e1eJag==/com.linagora.android.teammail-04CbRYbwzTXe3TdqGM2v6Q==/lib/arm/libflutter.so (BuildId: 9882e8056074409fcb06e2995e802c3c56ad0f5a)
Lost connection to device.
```

IMO, it crashed on tablet. please try to reproduce with tablet.

**Comment by dab246** [comment] 2023-03-15 02:19
- Emulator work fine
- We need to investigate further on real device

**Closed** 2023-03-29 19:25 UTC
Labels: bug, Critical
