### ISSUE TITLE
SearchSnippet can not find the text in some case

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#3282] opened 2024-11-19 04:19 UTC
### Desc:
- Env: tmail linagora
- Reproduce
   1. Search `barcamp`
   2. `Email/query` response to these messages
   3. `SearchSnippet` also response these messages but `preview` and `subject` still null

![Image](https://github.com/user-attachments/assets/c0fe6eea-1915-412a-b053-dbc3373c9206)

Please find the EMLs below

[Re_ CV_2023.03_W11_Nguyen Quang Minh_Mobile_FB.eml.txt](https://github.com/user-attachments/files/17809281/Re_.CV_2023.03_W11_Nguyen.Quang.Minh_Mobile_FB.eml.txt)
[\[Distributed Emailing Team\] Sprint 34 retrospective summary.eml.txt](https://github.com/user-attachments/files/17809280/Distributed.Emailing.Team.Sprint.34.retrospective.summary.eml.txt)

### Expect:
- [ ] should also have highlight text in these cases 

Cc: @Arsnael @vttranlina

**Comment by Arsnael** [comment] 2024-11-19 08:19
> Env: tmail linagora

Not released or even committed on master? I dont even see the SearchSnippet/get on the oncommit-tmail.linagora.com url... 

I will boot up postman ok but not ideal, could have precised :)

**Comment by Arsnael** [comment] 2024-11-19 08:59
So ok few things here @hoangdat 

- can you provide the request you use as well? Just to be sure it's fully correct. Just the response without initial request aint enough for a full diagnosis
- after checking it looks like to me that keywords in attachments aren't returned and highlighted by SearchSnippet, which corresponds to your first message. 
- second message no idea, I dont see an attachment to it but I could not reproduce something similar on my side so far.

Regarding the attachments, it's a decision we need to make: @chibenwa => do we return highlights on attachments as well or not?

Regarding the second case, I propose that our both teams sit down this week together to try and figure it out. Good?

**Comment by hoangdat** [comment] 2024-11-20 05:51
### Request:
```
{
  "using": [
    "urn:ietf:params:jmap:core",
    "urn:ietf:params:jmap:mail",
    "urn:apache:james:params:jmap:mail:shares"
  ],
  "methodCalls": [
    [
      "Email/query",
      {
        "accountId": "94db052675894262fb8644f9517aaf25e8246c5c2eae08b34da40b748f30ec0b",
        "filter": {
          "inMailbox": "a4d2aed0-a62b-11ef-82a5-9945e41adc32",
          "text": "barcamp"
        },
        "sort": [
          {
            "isAscending": false,
            "property": "receivedAt"
          }
        ],
        "limit": 20
      },
      "c0"
    ],
    [
      "SearchSnippet/get",
      {
        "accountId": "94db052675894262fb8644f9517aaf25e8246c5c2eae08b34da40b748f30ec0b",
        "filter": {
          "inMailbox": "a4d2aed0-a62b-11ef-82a5-9945e41adc32",
          "text": "barcamp"
        },
        "#emailIds": {
          "resultOf": "c0",
          "name": "Email/query",
          "path": "/ids/*"
        }
      },
      "c1"
    ],
    [
      "Email/get",
      {
        "accountId": "94db052675894262fb8644f9517aaf25e8246c5c2eae08b34da40b748f30ec0b",
        "#ids": {
          "resultOf": "c0",
          "name": "Email/query",
          "path": "/ids/*"
        },
        "properties": [
          "id",
          "blobId",
          "subject",
          "from",
          "to",
          "cc",
          "bcc",
          "keywords",
          "size",
          "receivedAt",
          "sentAt",
          "preview",
          "hasAttachment",
          "replyTo",
          "mailboxIds",
          "header:X-MEETING-UID:asText"
        ]
      },
      "c2"
    ]
  ]
}
```

And two these emails not have attachment. Keyword exists in body

**Comment by vttranlina** [comment] 2024-11-27 08:11
catched it, 
Backend bug, 
OpenSearch highlight missed a query on `HTML_BODY`. 
I'll create a PR to fix it.

**Comment by vttranlina** [comment] 2024-11-27 08:47
Fixup pr: 
- https://github.com/apache/james-project/pull/2524

**Closed** 2024-11-28 03:05 UTC
Labels: bug, search
