### ISSUE TITLE
Email text content could be temporarily truncated

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1961] opened 2023-06-22 06:16 UTC
### Current behavior

When I open this mail on mobile I can only read the top of the mail.

The bottom of the mail is truncated and thus cannot be read.

https://github.com/linagora/tmail-flutter/assets/6928740/2b8ed2b5-0d0a-4667-abef-dba16cd5d539

However after some time, (I had the phone on the side of the desk while opening the bug report) the full content loaded as shhown here:

https://github.com/linagora/tmail-flutter/assets/6928740/2134d062-6392-44ca-ba75-b5c8bf31619a

Happens only on mobile. No problem with WEB

https://github.com/linagora/tmail-flutter/assets/6928740/222dd92f-befc-44e3-b0c1-c329c79e5115

### Expected result

Can read the full email

https://github.com/linagora/tmail-flutter/assets/6928740/2823f4fa-6c78-47ca-9277-109e0a043923

### Context

Android TMail app, v 0.7.8

### Additional information

EML :  [truncated-eml.txt](https://github.com/linagora/tmail-flutter/files/11829480/truncated-eml.txt)

CC @QuangHoang1210 @hoangdat

**Comment by dab246** [comment] 2023-06-22 06:34
@chibenwa  please send again file `.eml`. Thank

**Comment by QuangHoang1210** [comment] 2023-06-22 07:37
@chibenwa  Can you send me your html in email body!?

This is the way how I created the new html email - but  I cannot reproduce the issue :(

https://github.com/linagora/tmail-flutter/assets/124866146/ebe7809b-bb4f-45ca-947d-edc72c7ed52b

-- View html email on android:

https://github.com/linagora/tmail-flutter/assets/124866146/6de04f93-9a32-47fa-a579-7fbeca27e975

**Comment by chibenwa** [comment] 2023-06-22 07:51
Both of you READ AGAIN THE BUG REPORT

**Comment by chibenwa** [comment] 2023-06-22 07:52
![Screenshot from 2023-06-22 14-52-05](https://github.com/linagora/tmail-flutter/assets/6928740/40baf82c-28e0-44fe-b480-f98ea01811cf)

**Comment by dab246** [comment] 2023-06-22 09:03
> Both of you READ AGAIN THE BUG REPORT

Why don't you compress it under the .eml file. File .txt it will be inaccurate and difficult for us to reproduce.

**Comment by chibenwa** [comment] 2023-06-22 09:14
Just rename the extension `.txt` into `.eml` locally?

**Comment by chibenwa** [comment] 2023-06-22 09:17
[Tr : Alexandre Blick Rothenberg Seminar: IR35 Regulations – the practical aspects - Alexandre ZAPOLSKY <azapolsky@linagora.com> - 2023-06-21 1936.zip](https://github.com/linagora/tmail-flutter/files/11832315/Tr.Alexandre.Blick.Rothenberg.Seminar.IR35.Regulations.the.practical.aspects.-.Alexandre.ZAPOLSKY.azapolsky%40linagora.com.-.2023-06-21.1936.zip)

**Comment by dab246** [comment] 2023-06-23 03:06
@chibenwa 

I have rechecked the error video you provided. At the 4th second (`0:04`). This is not an error, the data is still being downloaded. The loading bar is still visible, indicating that the email content has not been fully rendered to the screen. So we cannot scroll to the end of the content. And in the following video, the email content has been completely rendered so it can be scrolled.

<img width="298" alt="Screenshot 2023-06-23 at 09 59 39" src="https://github.com/linagora/tmail-flutter/assets/80730648/85769d3b-ee7a-4b58-a4aa-2fcfd910c5e2">

I have to admit the loading bar is gray so it's hard to see for the user. We will come up with a plan to improve this.

Finally you can test it again by opening the email and waiting for the loading bar to disappear you will be able to scroll the email.

**Comment by QuangHoang1210** [comment] 2023-06-23 03:07
https://github.com/linagora/tmail-flutter/assets/124866146/f8a9dbbb-d186-4a03-93ca-2a5bebc6674e

This is not a bug. System is loading about 50 seconds then the email is load sucessfully to scroll down to view. <Both ios & android>

-- Should improve UX

**Comment by hoangdat** [comment] 2023-06-23 05:17
IMO, we should more investigate on this issue, how to have better solution for this kind of email. Sure, for us not a big problem but with some decision maker, a not acceptable UX. Majox one.

**Comment by chibenwa** [comment] 2023-06-23 05:24
> This is not a bug. System is loading about 50 seconds then the email is load sucessfully to scroll down to view.

Then that's a bug ^^

**Closed** 2023-08-22 20:10 UTC
Labels: bug, Major
